### ISSUE TITLE
Deleting a screen fails

### ISSUE THREAD

**Issue by sheosanjay** [microsoft/PowerApps-Samples#185]
I am not able to delete a complete screen  or components within the screen such as forms, labels, fields, icons etc. it keeps on rotating as saving but deletion does not work.

**Comment by Nkrb** [comment]
@sheosanjay Can you point us to the sample that you are facing the issue.

**Comment by phecke** [comment]
@sheosanjay Since this issue was opened so long ago I assume you got past this problem, therefore I am closing the issue. If you are still having trouble, file an new issue. However, we only take issues here for sample code. If this is a support issue with the products, you should file a support request or post to one of the developer forums.

**Comment by sheosanjay** [comment]
I am working on a spp which has 3 sp list as data source. I developed 2
screens and copied a third screen from my colleagues app. On copying the
screen, I found screen cannot be copied but form within a screen can be
copied. Later when I tried to edit the form it was taking longer time and
failed to open in edit  mode. This is the situation I am not able to edit
or delete the screen. If fields labels or forms are deleted from screen , I
cannot save the app..this is my challenge I stuck with.
