### ISSUE TITLE
Height of mda grid doesn't adjust and ribbon buttons are missing

### ISSUE THREAD

**Issue by hansgfixed** [microsoft/PowerApps-Samples#241]
Hi Scott, 

I'm currently working with your [MDA Grid](https://github.com/microsoft/PowerApps-Samples/blob/master/component-framework/ModelDrivenGridControl/ModelDrivenGrid/Grid.tsx) sample and the height is always -1 and the ribbon buttons of the subgrid are completely missing when I register yours. Any ideas? Let me know if you need further input.

Thank you in advance and cheers

**Comment by scottdurow** [comment]
Hi @hansgfixed,
The allocatedHeight will be -1 because it's expected that the code component expands to use the available space (https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/mode/trackcontainerresize) the only exception to this is when using with a form subgrid where the form does not allocate any height and so the component must expand to a specific height - this is where the sample uses the property `SubGridHeight` https://github.com/microsoft/PowerApps-Samples/blob/master/component-framework/ModelDrivenGridControl/ModelDrivenGrid/index.ts#L137

Where are you seeing the command bar missing - home/subgrid or form subgrid? Normally this would be controlled by the cds-data-set-options attribute on the data-set - https://github.com/microsoft/PowerApps-Samples/blob/ef8cbed1e6c563c839caf0caf601b52392c6928e/component-framework/ModelDrivenGridControl/ModelDrivenGrid/ControlManifest.Input.xml#L17

**Comment by hansgfixed** [comment]
Hi @scottdurow, 

thank you for your quick response.

When I created a new pcf of field type dataset the cds props were actually missing. Good hint! And your input regarding the subgrid height for using the sample pcf on a form subgrid makes now sense to me. Now everything is working as expected.

Thanks for helping me out.
