### ISSUE TITLE
CanvasGridControl sample build failed

### ISSUE THREAD

**Issue by DavidPaf** [microsoft/PowerApps-Samples#254]
Performed steps in the guide: https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework#how-to-run-the-sample-components

Error at step: 

msbuild /t:restore
msbuild /t:rebuild /restore /p:Configuration=Release

Error message:
Microsoft.PowerApps.MSBuild.Solution.targets(134,5): error : Value cannot be null

![image](https://user-images.githubusercontent.com/61499598/161190113-60526207-4a21-435c-a6b7-a4fdb1f4225b.png)

**Comment by JimDaly** [comment]
@DavidPaf 
Sorry for responding so late. 
I tested the steps and am not able to reproduce the error you experienced.
The only difference in the steps I used from the instructions is that I used VS 2019 Developer command prompt, but that shouldn't make any difference.

If you are still experiencing this, please contact technical support.
If you have found the source of the problem, please share it so that we might guide others to avoid it.
