### ISSUE TITLE
WebAPIService usage for MS Dynamics CRM

### ISSUE THREAD

**Issue by ilazarevski** [microsoft/PowerApps-Samples#328]
Hello,

is it possible to use the **WebAPIService** for on-premise MS Dynamics CRM?

Thank you in advanced.

Kind regards,
Ilija.

**Comment by JimDaly** [comment]
@ilazarevski 

The [WebAPIService class library](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/webapiservice) is a sample that demonstrates recommended practices, such as managing service protection limits, etc. It is a resource to learn from, not something we expect people to use in production 'as-is'.

I haven't done any testing with on-premises, but I expect it should work. You will need to change the version in the configuration because it currently defaults to v9.2, which is only online. On-premises would be v9.1.

If you are already using .NET, I would recommend using the SDK. If you want to use .NET Core, then I would recommend using Dataverse ServiceClient. See [Transition apps to Dataverse ServiceClient](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/sdk-client-transition). ServiceClient (and CrmServiceClient) manage service protection limits, has advanced capabilities for logging and is supported for use in your production environment.

I hope this helps. Let me know if you have any other questions.
