### ISSUE TITLE
Grid Customizer not working

### ISSUE THREAD

**Issue by WhiteyC** [microsoft/PowerApps-Samples#381]
I have copied the exact sample for the Power Apps Grid custom control and it executes the custom code but no visible UI changes occur on text or currency. Please advise next steps?

**Comment by JimDaly** [comment]
@WhiteyC 
Can you clarify which sample you are referring to?

Is it the one mentioned here [Customized editable grid](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/sample-controls/customized-editable-grid-control)?
With the sample code from here: [https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/PowerAppsGridCustomizerControl](https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/PowerAppsGridCustomizerControl)

I think next steps are to use the steps here to debug and understand the issue better [Debug code components](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/debugging-custom-controls)

If you identify a specific issue, please let us know.

**Comment by WhiteyC** [comment]
> @WhiteyC Can you clarify which sample you are referring to?
> 
> Is it the one mentioned here [Customized editable grid](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/sample-controls/customized-editable-grid-control)? With the sample code from here: https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/PowerAppsGridCustomizerControl
> 
> I think next steps are to use the steps here to debug and understand the issue better [Debug code components](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/debugging-custom-controls)
> 
> If you identify a specific issue, please let us know.

Yes, I am using the Grid Customizer Control. I have added a debugger; in the "int" and that triggers fine. However the cell render does nothing.

export const cellRendererOverrides: CellRendererOverrides = {
    ["Text"]: (props, col) => {
        // Render all text cells in green font
        return <Label style={{ color: 'green' }}>{props.formattedValue}</Label>
    }
}


    public init(
        context: ComponentFramework.Context<IInputs>,
        notifyOutputChanged: () => void,
        state: ComponentFramework.Dictionary
    ): void {
        debugger;
        const eventName = context.parameters.EventName.raw;
        if (eventName) {
            const paOneGridCustomizer: PAOneGridCustomizer = { cellRendererOverrides, cellEditorOverrides };
            (context as any).factory.fireEvent(eventName, paOneGridCustomizer);
        }
    }

The control builds fine and deploys fine. Added to Power apps grid control as a customizer.

**Comment by brasov2de** [comment]
I've seen the same. It started suddenly, probably because of a Platform update last Sunday night. 
It happended that the control I was developing worked, and a few minutes later, without any change, it stopped working.
I have also older controls which worked before: all of them stopped working since then.

**Comment by WhiteyC** [comment]
> I've seen the same. It started suddenly, probably because of a Platform update last Sunday night. It happended that the control I was developing worked, and a few minutes later, without any change, it stopped working. I have also older controls which worked before: all of them stopped working since then.

Good to see I'm not the only one going through this. It's the latest update on the Power Apps Grid control.

**Comment by JimDaly** [comment]
@WhiteyC  & @brasov2de 

Adding @HemantGaur 

It sounds like you are describing an issue that is larger than this specific sample. This sounds like a platform level issue rather than something we can address by changing this sample code. Am I understanding you correctly?

In this case, it is important that you contact technical support and report the issue. We don't have the resources to troubleshoot this with you.

If there is an issue with a specific sample, then we do want to get that sample fixed. Otherwise, this isn't the appropriate place to look for technical support.

**Comment by JimDaly** [comment]
I notified @HemantGaur and there seems to be a corresponding known issue in production.
Not yet sure if the fix is deployed to all regions at this point.

Since there is nothing actionable related to this sample code, I'm going to close this issue.

**Comment by morgutrin** [comment]
@JimDaly is there any info about when fix will be released?

**Comment by jasongre** [comment]
@morgutrin / @WhiteyC  / @brasov2de This fix will be available by late March for most geos.

**Comment by WhiteyC** [comment]
> @morgutrin / @WhiteyC / @brasov2de This fix will be available by late March for most geos.

Can I ask where you found this information in regards to a fix?

**Comment by JimDaly** [comment]
@WhiteyC 

@jasongre is the program manager for this feature.

**Comment by WhiteyC** [comment]
> @WhiteyC
> 
> @jasongre is the program manager for this feature.

Thanks Jim. That's not giving me any confidence in MS support as I have a case raised on this and they have not given me any information of this kind. Not helpful when you are trying to earn a living with this product and have deadlines.

**Comment by mianfriH** [comment]
Hello everyone, I am having a problem with the controlcustomizer and the column filters. I explain... When I filter some of the columns, sometimes, many times, the funnel icon and the option to clean filters, disappear from the column header. And the times that they don't disappear, when I clean filters, all the results are not shown again. In other words, it is as if I only get the filter the first time and the grid remains with that filter until I refresh the page.

Any help on this would be very welcome. This problem is driving me crazy and is going to force me to remove a control that has taken me many hours of development.

Thanks.
