### ISSUE TITLE
VS 2019 Not supported?

### ISSUE THREAD

**Issue by bpasham** [microsoft/PowerApps-Samples#88]
For component framework samples (PCF)
.pcfproj extension doesn't seem to be supported by VS2019 and, since these are in typescript anyway, no instructions for VSCode using PCF samples. Instructions says use MSBuild.. really?

Can we have validated instructions that work please!

**Comment by KumarVivek** [comment]
@Nkrb Can you address this issue.

**Comment by ghurlman** [comment]
@bpasham Currently yes, the only way to build a PCF project is with the command line interface; you _can_ use VS Code as it has all the TypeScript knowledge it needs out of the box for things like errors, warnings, intellisense, etc. However, you must still use the command line (either separately or within VS Code) to do your builds, including using msbuild to package things up for deployment.

We have heard the need for a VS2019 or otherwise non-CLI solution for building and packaging these projects, and are tracking that feedback for our future plans.

**Comment by bpasham** [comment]
My main concern is that the instructions are very inconsistent. You have instructions for VS2017, no support for VS2019 and no instructions for VSCode.. anywhere usable. Because Vs2017 instructions are for MSBuild.... that are usable straight forward for VSCode users, lots of dependencies and platform dependencies... which are not clarified anywhere. Hope you understand what is going on in the real world of application development.

**Comment by bpasham** [comment]
in short -- I am looking for CLI instructions which are not missing.

**Comment by ghurlman** [comment]
@bpasham -- The instructions are not different for VSCode or VS2019 -- currently, the MSBuild command line tools are used to package your component, regardless of IDE.

I will review the initial setup docs again, and get things clarified as needed.
